export const THEME: {
  BLACK: string,
  WHITE: string,
} = {
  BLACK: 'black',
  WHITE: 'white',
};

export const FONTS: {
  H1: number,
  H2: number,
  H3: number,
  H4: number,
  H5: number,
  H6: number,
  P1: number,
  P2: number,
  P3: number,
} = {
  H1: 30,
  H2: 25,
  H3: 20,
  H4: 18,
  H5: 16,
  H6: 15,
  P1: 14,
  P2: 13,
  P3: 12,
};

export const DARK_THEME: {
  dark: boolean,
  colors: {
    primaryColor: string,
    secondaryColor: string,
    color: string,
    textColor: string,
    modalColor: string,
    headerColor: string,
    drawerBackgroundColor: string,
    searchBoxBackgroundColor: string,
    linkColor: string,
    sentByMeCardColor: string,
    receivedCardColor: string,
    sentByMeLinkColor: string,
    recivedLinkColor: string,
    sentByMeTextColor: string,
  },
} = {
  dark: true,
  colors: {
    primaryColor: '#121212',
    secondaryColor: '#b3b3b3',
    color: 'white',
    textColor: 'white',
    modalColor: '#252525',
    headerColor: '#333333',
    drawerBackgroundColor: '#1A2421',
    searchBoxBackgroundColor: '#262626',
    linkColor: '#F4C430',
    sentByMeCardColor: '#007AFF',
    receivedCardColor: '#353535',
    sentByMeLinkColor: 'white',
    recivedLinkColor: '#F4C430',
    sentByMeTextColor: 'white',
  },
};

export const LIGHT_THEME: {
  dark: boolean,
  colors: {
    primaryColor: string,
    secondaryColor: string,
    color: string,
    textColor: string,
    modalColor: string,
    headerColor: string,
    drawerBackgroundColor: string,
    searchBoxBackgroundColor: string,
    linkColor: string,
    sentByMeCardColor: string,
    receivedCardColor: string,
    sentByMeTextColor: string,
    sentByMeLinkColor: string,
    recivedLinkColor: string,
  },
} = {
  dark: false,
  colors: {
    primaryColor: '#ffffff',
    secondaryColor: 'black',
    color: 'black',
    textColor: 'black',
    modalColor: 'white',
    headerColor: 'white',
    drawerBackgroundColor: 'white',
    searchBoxBackgroundColor: 'white',
    linkColor: '#F4C430',
    sentByMeCardColor: '#087FFF',
    receivedCardColor: '#E9E9EB',
    sentByMeTextColor: 'white',
    sentByMeLinkColor: 'white',
    recivedLinkColor: 'blue',
  },
};
